# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Flutter App

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: "Select build flavor"
        required: true
        type: environment

jobs:
  build:
    runs-on: macos-latest
    environment: ${{ github.event.inputs.flavor }}
    env:
      FLAVOR: ${{ github.event.inputs.flavor }}
      APP_DISPLAY_NAME: ${{ vars.APP_DISPLAY_NAME }}
      ANDROID_APP_ID: ${{ vars.ANDROID_APP_ID }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      # BUILD_NUMBER: ${{ github.event.inputs.build_number }}
      # ENABLE_OBFUSCATION: ${{ github.event.inputs.enable_obfuscation }}
 
    steps:
      - name: Create release.jks from secret
        run: |
          # Make sure folder exists
          mkdir -p android/app
          
          # Decode base64 secret into the keystore file
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/release.jks
          
          # Export path so Gradle can use it
          echo "STORE_FILE=android/app/release.jks" >> $GITHUB_ENV
          
          # Optional: log success
          echo "âœ… Keystore file created at $STORE_FILE"

      - name: STORE_FILE path
        run: echo "STORE_FILE is $STORE_FILE"

      - name: build values
        run: echo "Flavor is $FLAVOR, APP_NAME is $APP_DISPLAY_NAME"

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml

      - name: Check Flutter version
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      # - name: Analyze project source
      #   run: dart analyze
      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      # - run: flutter build appbundle
