# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Flutter App

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: "Select build flavor"
        required: true
        type: environment

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.flavor }}
    env:
      FLAVOR: ${{ github.event.inputs.flavor }}
      APK_PATH: build/app/outputs/flutter-apk/app-${{ github.event.inputs.flavor }}-release.apk
      APP_DISPLAY_NAME: ${{ vars.APP_DISPLAY_NAME }}
      ANDROID_APP_ID: ${{ vars.ANDROID_APP_ID }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      # BUILD_NUMBER: ${{ github.event.inputs.build_number }}
      # ENABLE_OBFUSCATION: ${{ github.event.inputs.enable_obfuscation }}
 
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Create google-services.json for flavor $FLAVOR
        run: |
            mkdir -p android/app/src/$FLAVOR
            echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 --decode > android/app/src/$FLAVOR/google-services.json

      - name: Create release.jks from secret
        run: |
          mkdir -p android/app
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/release.jks
          echo "STORE_FILE=release.jks" >> $GITHUB_ENV

      - name: STORE_FILE path
        run: echo "STORE_FILE is $STORE_FILE"

      - name: Verify keystore file exists
        run: |
          ls -lh android/app/release.jks

      - name: build values
        run: echo "Flavor is $FLAVOR, APP_NAME is $APP_DISPLAY_NAME"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml

      - name: Check Flutter version
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      # - name: Analyze project source
      #   run: dart analyze
      - name: Build APK
        run: flutter build apk --flavor $FLAVOR --release

      - name: Upload APK to Git Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/*.apk
      # - run: flutter build appbundle

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: $FIREBASE_APP_ID
            serviceCredentialsFileContent: $FIREBASE_SERVICE_ACCOUNT
            groups: cicd-test-group
            file: build/app/outputs/flutter-apk/*.apk
            releaseNotes: |
              ðŸš€ New Release Build
              - Bug fixes
              - Performance improvements
              - Updated UI changes
